### ISSUE TITLE
Optimized PV inversion for two layer case in `MultilayerQG`

### ISSUE THREAD

**Issue by glwagner** [FourierFlows/GeophysicalFlows.jl#267]
Currently we implement "optimized" functions for extracting PV from the QG streamfunction, and vice versa, in the single layer case:

https://github.com/FourierFlows/GeophysicalFlows.jl/blob/f4c68a58556f512c7118490fcb98679e68fff522/src/multilayerqg.jl#L485-L495

The inversion is also trivial in the two layer case, so we should support that.

To implement this I propose generalize `SingleLayerParams` to `NLayerParams{N, ...}`, where `N` is the number of layers. Then we have aliases

```julia
const SingleLayerParams = NLayerParams{1}
const TwoLayerParams = NLayerParams{2}
```

and we can implement optimized inversion routines for these two cases.

cc @szy21

**Comment by navidcy** [comment]
This is a duplicate or related to #112

**Comment by navidcy** [comment]
We should resolve this! It’ll make the MultiLayerQG so much faster!

**Comment by glwagner** [comment]
It's related to #112 but not a duplicate. #112 is about accelerating the arbitrary-layer case. This issue is about accelerating the two layer case.

**Comment by glwagner** [comment]
I think even if #112 is somehow resolved (eg by using KernelAbstractions --- a good solution for that issue still isn't clear to me), we probably still want to implement a special optimized method for two layer case.
